version: '3.8'

services:
  saiso_app:
    build: .
    container_name: saiso_bot
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./instance:/app/instance
      - ./.env:/app/.env
    environment:
      - TZ=Asia/Seoul
